### PR TITLE
Bump 1.2.1

### PR DESCRIPTION
**Pull request by nsteinmetz**
Update to Traefik 1.2.1

### CODE REVIEW

**Comment by firecyberice** [comment]
can you please add ca-certificates again to fix #20

**Comment by nsteinmetz** [comment]
Yes of course, will add it immediatly !

**Comment by nsteinmetz** [comment]
Here you are and sorry for breaking things, I thought ca-certificates was required to fetch arm build on github only :-/

**Comment by firecyberice** [comment]
LGTM

**Pull request merged**
