### PR TITLE
Update Dockerfile with 1.0.3 release

### PR DESCRIPTION
**Pull request by nsteinmetz**
Bump version with 1.0.3

Is someone interested by the 1.1RC too ?

### CODE REVIEW

**Comment by jmshal** [comment]
> Is someone interested by the 1.1RC too ?

1.1 rc would be 🤘

**Comment by nsteinmetz** [comment]
Ok, I will provide this but maybe with my own repo to be more reactive on this... I'll let you know.

**Comment by StefanScherer** [comment]
Thank you!

**Comment by nsteinmetz** [comment]
@jacobmarshall have a look at https://hub.docker.com/r/nsteinmetz/traefik-arm/tags/, You have a `1.1.0-rc3` tag and up to date Dockerfile is on my [fork](https://github.com/nsteinmetz/rpi-traefik), till PR  #5 is merged.

**Comment by jmshal** [comment]
Cheers mate!

**Pull request merged**
