### PR TITLE
Move to Alpine 3.4 instead of 3.2

### PR DESCRIPTION
**Pull request by nsteinmetz**
Just saw that tags for rpi-alpine-scratch contains v3.4 - latest is sticked with 3.2 - it may need an update.

### CODE REVIEW

**Comment by nsteinmetz** [comment]
Too many commits for at the end noticing I should have watched tags for docker image rpi-apline-scratch...

Time to sleep :)

**Comment by firecyberice** [comment]
We should maybe switch to `armhf/alpine:3.4` as base image

**Comment by nsteinmetz** [comment]
As you prefer, it can be done easily. The point for me is only to have a maintained and stable version of alpine.

I also found yesterday `orax/alpine-armhf` but updated on a daily basis, it's maybe a little bit too much.

I'll rebase my dockerfile on `armhf/alpine:3.4` later today then and update PR.

**Comment by nsteinmetz** [comment]
Rebase to `armhf/alpine` done :)

**Pull request merged**
