### PR TITLE
Switch to rpi-alpine:3.6

### PR DESCRIPTION
**Pull request by nsteinmetz**

### CODE REVIEW

**Comment by nsteinmetz** [comment]
I assume failed tests are due to branch name - @StefanScherer you confirm ?

If not, we'll revert ;-)

**Comment by nsteinmetz** [comment]
Weird, seems pushed despite travis reporting an error ?!
https://hub.docker.com/r/hypriot/rpi-traefik/tags/ is updated.

**Comment by StefanScherer** [comment]
No, it's not the branch name, Travis has problems with QEMU and the base image:

```
runtime: failed to create new OS thread (have 2 already; errno=22)
```

We have changed both QEMU 2.6.0->2.9.1 and the base image in rpi-alpine. Let's try to revert one of it.

**Comment by nsteinmetz** [comment]
Ok will check later this weekend

**Comment by nsteinmetz** [comment]
I just did the revert - Will fix this after my summer break in august ;-)

**Pull request merged**
