### PR TITLE
Bump 1.3.2

### PR DESCRIPTION
**Pull request by nsteinmetz**

### CODE REVIEW

**Comment by StefanScherer** [comment]
Thank you @nsteinmetz 
I would like to add you as a collaboratour as you have added the most of the commits in this repo. Check your inbox 👍

**Comment by nsteinmetz** [comment]
Hi @StefanScherer 

W00t, just accepted it :-)

**Comment by StefanScherer** [comment]
So this PR LGTM, so you can merge it 🚀

**Comment by nsteinmetz** [comment]
... and done :ok_hand:

**Comment by StefanScherer** [comment]
Great, Travis will build and push the image.

**Pull request merged**
